### ISSUE TITLE
HTTPS on nginx-ldap-auth-daemon

### ISSUE THREAD

**Issue by yzargari** [linuxserver/docker-ldap-auth#28]
Since the traffic between nginx and ldap-auth contains the most sensitive info (passwords) - I'd like to set it up with SSL encryption (https). I was able to add this to the root/app/nginx-ldap-auth-daemon.py file, so I'm wondering if you'd consider accepting this as PR (I don't have permissions to create a branch andPR).

Thanks,
Yosi

**Comment by aptalca** [comment]
You can fork and PR and we'll take a look
Normally, we recommend having them talk to each other via the docker network (user defined bridge)

**Comment by yzargari** [comment]
I'm running this in Kubernetes, and I'll have multiple nginx servers needing this component, so I thought it'd be better to run the ldap-auth daemon as a standalone deployment (with autoscaling) to service all nginx servers - meaning traffic will be on the network...

**Comment by yzargari** [comment]
I created PR #29 for this. Thanks for looking into it.

**Comment by drizuid** [comment]
I'm confused as to what is not working... I leverage this for LDAPS and i've tested it with STARTTLS with public and internal CA certs. 
https://github.com/linuxserver/docker-ldap-auth/pull/24

I'm running around like crazy at the moment, but what am I missing here? 

connect to reverse proxy via ssl, reverse proxy tells you to use /ldaplogin and passes to ldap-auth container, ldap-auth speaks to ldap server via LDAPS or STARTTLS. Are you just indicating the lack of trust that potentially exists between nginx and ldap-auth?
