### ISSUE TITLE
Container fails to start if CERTFILE or KEYFILE are not set

### ISSUE THREAD

**Issue by crobibero** [linuxserver/docker-ldap-auth#30]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Container should start without error.

## Current Behavior

Container throws exception and fails to start.

## Steps to Reproduce

1. Start container with base docker-compose from example.
2. View error.

## Environment
**OS:**  Debian 9    
**CPU architecture:** x86_64
**How docker service was installed:**  Normal

## Command used to create docker container (run/create/compose/screenshot)

```
ldap-auth:
	container_name: ldap-auth
	image: linuxserver/ldap-auth:latest
	restart: always
	environment:
		- TZ=America/New_York
		- PGID=1001
		- PUID=1001
```
## Docker logs

```
Traceback (most recent call last):
  File "/app/nginx-ldap-auth-daemon.py", line 339, in <module>
    if os.path.isfile(os.environ.get("CERTFILE")) and os.path.isfile(os.environ.get("KEYFILE")):
  File "/usr/lib/python3.8/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

## Additional Information
Caused by https://github.com/linuxserver/docker-ldap-auth/pull/29

**Comment by aptalca** [comment]
@yzargari ^^

**Comment by yzargari** [comment]
> @yzargari ^^

I had the same problem when did regression test and did fix it, but probably didn't include that commit in the PR. I sincerely apologize for creating this bug.

**Comment by aptalca** [comment]
no worries, it's fixed now
