### ISSUE TITLE
Login with /ldaplogin requires /login to be reverse-proxied

### ISSUE THREAD

**Issue by dpraul** [linuxserver/docker-ldap-auth#32]
## Expected Behavior

Login should work from `/ldaplogin` without `/login` reverse-proxied to the image.

## Current Behavior

The page redirects to `/login` after pressing "Log In" or pressing enter.

I believe this is because the [form action in the login page is set to `/login`](https://github.com/linuxserver/docker-ldap-auth/blob/63fef098f8916d50ed9faf0f349f689a92b5dcc8/root/app/ldap-backend-app.py#L91), so unless both `/login` and `/ldaplogin` are forwarded to the application, the image will not receive the POST request from `/ldaplogin`.

**Comment by aptalca** [comment]
Yup, we missed that. Thanks for the heads up.

**Comment by lloydpick** [comment]
Just to add on this, if you use the nginx proxy templates you can't login anymore. As they all use the new path and the swag config just has ldaplogin as the reversed path.
