### ISSUE TITLE
30-config breaks on a FERNETKEY with a slash

### ISSUE THREAD

**Issue by ncraike** [linuxserver/docker-ldap-auth#41]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Given a `FERNETKEY` environment variable with base64-encoded 32-bytes, the `ldap-auth` container should start successfully, and use the given bytes as the Fernet key for encoding/decoding auth tokens.

## Current Behavior
*If* the `FERNETKEY` environment variable contains a forward-slash as part of the base64-encoded value, the container gives these errors on startup:
```
[cont-init.d] 30-config: executing... 
using FERNETKEY from env variable
sed: bad option in substitution expression
sed: bad option in substitution expression
```
…and then other errors on handling requests:
```
Traceback (most recent call last):
  File "/app/nginx-ldap-auth-daemon.py", line 88, in do_GET
    cipher_suite = Fernet(REPLACEWITHFERNETKEY)
NameError: name 'REPLACEWITHFERNETKEY' is not defined
```

## Steps to Reproduce
1. Run the Docker container with the `FERNETKEY` environment variable containing 32-bytes base64-encoded, with the base64 encoding including a forward slash (`/`).  

## Environment
**OS:** CentOS Linux release 7.9.2009
**CPU architecture:** x86_64
**How docker service was installed:**
Pulled from `ghcr.io/linuxserver/ldap-auth:latest`

## Command used to create docker container (run/create/compose/screenshot)
In Portainer / Docker Swarm, with `docker-compose.yaml` like:
```
  ldap-auth:
    deploy:
      mode: replicated
      replicas: 2
    image: ghcr.io/linuxserver/ldap-auth:latest
    environment:
      - TZ=Australia/Brisbane
      - FERNETKEY=oBKkF1GPSCmiWgCliTvd1ITScu2GYYXFRYo/Wm/vMNg=
    ports:
      - "8888:8888"
      - "9000:9000"
 ```

## Docker logs
[docker_logs.txt](https://github.com/linuxserver/docker-ldap-auth/files/6420147/docker_logs.txt)

## Notes
The [cryptography docs](https://cryptography.io/en/latest/fernet/) actually describe the `Fernet` class expecting a "URL-safe base64-encoded 32-byte key". If I had used [the URL-safe variant](https://docs.python.org/3.6/library/base64.html?highlight=base64#base64.urlsafe_b64encode) of base64 to encode the bytes, this would have worked fine.

However:
 - The docs for *this container* don't mention "URL-safe", so I used the standard base64 encoding, which uses `/` as one of the encoding characters.
 - In testing, the `Fernet` class actually seems to accept non-URL-safe base64 encoding. If it didn't, the testing at line 8 of `30-config` would've failed, the container would ignore the provided Fernet key and generate its own, and we wouldn't see an error from `sed`.

## Suggested fix
- update the container docs to specify *URL-safe* base64-encoding.
- change `30-config` to use `sed -i "s#REPLACEWITHFERNETKEY#${KEY}#" <file path>`, so it doesn't break on a forward-slash regardless. `sed` can use any character as a delimiter for a find-replace command, it doesn't have to be `/`.

**Comment by aptalca** [comment]
Thanks for the detailed issue, but the definition of fernet key (as you linked above) states url safe, so I don't feel the need to repeat all that here.

That var is optional, you don't need to provide a fernet key at all as it is auto generated. The only reason we added that var is because the following PR made a case for a need in some fringe circumstances: https://github.com/linuxserver/docker-ldap-auth/pull/27

If you are setting a fernet key, you are expected to create a valid one like we do here: https://github.com/linuxserver/docker-ldap-auth/blob/master/root/app/fernet-key.py

**Comment by ncraike** [comment]
Right. I was initially reading the documentation of the Docker image, [which has](https://docs.linuxserver.io/images/docker-ldap-auth#environment-variables-e):

> `FERNETKEY=`
> Optionally define a custom fernet key, has to be base64-encoded 32-byte (only needed if container is frequently recreated, or if using multi-node setups, invalidating previous authentications)

I used Python's `base64.b64encode(secrets.token_bytes(32))` to generate the Fernet key, as I wasn't aware of the `fernet-key.py` script until I dug into the image source a little.

Similar to #27, we're running the container in Docker Swarm, with two instances of the container spread across multiple nodes, and some occasional restarts. We were having issues with invalid tokens because of mismatched/changing keys.
