### ISSUE TITLE
[BUG] Cannot set ldap.OPT_REFERRALS, 0

### ISSUE THREAD

**Issue by grrttedwards** [linuxserver/docker-ldap-auth#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When this fork was made, the code to disable referrals was commented out

Compare upstream:
https://github.com/nginxinc/nginx-ldap-auth/blob/c98eb555f5faba6b6efdddad4071afa56464d2c5/nginx-ldap-auth-daemon.py#L231-L233

With this project:
https://github.com/linuxserver/docker-ldap-auth/blob/26f790dee26fa4a1b16764bce562200384f912f1/root/app/nginx-ldap-auth-daemon.py#LL238C57-L238C57

The example config shows how to, and my use case requires this:
https://github.com/nginxinc/nginx-ldap-auth/blob/c98eb555f5faba6b6efdddad4071afa56464d2c5/nginx-ldap-auth.conf#L112-L115

### Expected Behavior

Referrals cannot be disabled

**Comment by aptalca** [comment]
Do you mind opening a PR with the upstream changes?

**Comment by grrttedwards** [comment]
Done via https://github.com/linuxserver/docker-ldap-auth/pull/50
